name: update
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://someonewhocares.org/hosts/zero/hosts
          sed -i '/<localhost>/,/<\/localhost>/d' hosts
          sed -i 's/0.0.0.0//g' hosts
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase true
          git pull origin workflow
          git add .
          git commit -m "updated"
          git push