name: update
on:
  push:
  schedule:
    - cron:  '14 03 */1 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check for file updates
        uses: actions/checkout@v2
      - run: |
          sleep 1 # catch a breath
          echo "Checkout existing file..."
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase true
          git pull origin main
          sleep 1 # catch a breath
          echo "Download new file..."
          wget https://someonewhocares.org/hosts/zero/hosts -O list.tmp
          sed -i '/<localhost>/,/<\/localhost>/d' list.tmp
          sed -i 's/0.0.0.0//g' list.tmp
          sleep 1 # catch a breath
          echo "Check if file needs updating..."
          if [[ $(shasum list | awk '{print $1}') == $(shasum list.tmp | awk '{print $1}') ]]; then
            sleep 1 # catch a breath
            echo "Repository up to date!"
            rm list.tmp
            exit 0
          else
            sleep 1 # catch a breath
            echo "Repository needs updating..."
            mv list.tmp list
            git add .
            git commit -m "updated"
            git push origin HEAD:main && echo "Repository updated!"
            exit 0
          fi
