name: update
on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase true
          git pull origin main
          wget https://someonewhocares.org/hosts/zero/hosts -O list
          sed -i '/<localhost>/,/<\/localhost>/d' list
          sed -i 's/0.0.0.0//g' list
          echo \#`date +%s` >> list
          git add .
          git commit -m "updated"
          git push origin HEAD:main

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          job_name: Terratesting VPC Module
          fields: repo,message,commit,author,ref,workflow 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'action-slack',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} succeeded in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}